package controleur;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import Connexion.Connexion;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.stage.Stage;

public class adduserController {
	@FXML
	private TextField tuser;
	@FXML
	private TextField tpssword;
	@FXML
	private Button btnajouter;

	// Event Listener on Button[#btnajouter].onAction
	@FXML
	public void Actajouter(ActionEvent event) {
		// TODO Autogenerated
		if (tuser.getText().isEmpty() || tpssword.getText().isEmpty()) {
			Alert alert = new Alert(AlertType.INFORMATION);
			alert.setHeaderText("Error de validation de formulaire");
			alert.setContentText("Remplir tous les champs ");
			alert.showAndWait();
		} else {
			Connection con = Connexion.getConnection();

		
			PreparedStatement stat;
			ResultSet rs;
			String sql = "insert into user (username,password) values (?,?)";
			try {
				stat = con.prepareStatement(sql);
				stat.setString(1, tuser.getText().toString());
				stat.setString(2, tpssword.getText().toString());

				int res = stat.executeUpdate();
				if (res > 0) {
	                Alert successAlert = new Alert(AlertType.INFORMATION);
	                successAlert.setHeaderText("Ajout effectué avec succès");
	                successAlert.setContentText("L'utilisateur a été ajouté à la base de données.");
	                successAlert.showAndWait();

	                // Close the add user window
	                Stage stage = (Stage) btnajouter.getScene().getWindow();
	                stage.close();
	            } else {
	                Alert errorAlert = new Alert(AlertType.ERROR);
	                errorAlert.setHeaderText("Erreur lors de l'ajout de l'utilisateur");
	                errorAlert.setContentText("Une erreur s'est produite lors de l'ajout de l'utilisateur à la base de données.");
	                errorAlert.showAndWait();
	            }
	     
	    }
				
				
				
			
			catch (SQLException e) {
				e.printStackTrace();
				System.out.println("erreur " + e.getMessage());
			}
		}
	}
}
